config/routes.rb
Rails.application.routes.draw do
  resources :comment, only: [:create, :destroy]
  resources :board, only: [:new, :create, :index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :board
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/board_controller.rb
class BoardController < ApplicationController
  def index
    @boards = Board.all
  end

  def show
    @board = Board.find(params[:id])
    @comment = @board.comments.new
    @comments = @board.comments.all
  end

  def new
    @board = Board.new
  end


  def create
    @board = Board.new(board_params)
    if @board.save
      redirect_to @board
    else
      render :new
    end
  end

  def board_params
    params.require(:board).permit(:name)
  end
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      redirect_to board_path(@comment.board_id)
    else
      @board = @comment.board
      render template: 'board/show'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to board_path(@comment.board_id)
  end

  def comment_params
    params.require(:comment).permit(:content, :board_id, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_helper.rb
module BoardHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/views/board/index.html.erb
<h1>Board#index</h1>
<p>Find me in app/views/board/index.html.erb</p>

<% @boards.each do |board| %>
  <%= board.name %>: <%= link_to("板に行く", board) %><br>
<% end %>

<%= link_to("新規作成", new_board_path) %>

app/views/board/new.html.erb
<h1>Board#new</h1>
<p>Find me in app/views/board/new.html.erb</p>

<%= form_for(@board, url: :board_index) do |f| %>
  <%= f.text_field :name, placeholder: 'nameを入力してください' %>
  <%= f.submit %>
<% end %>

app/views/board/show.html.erb
<h1><%= @board.name %></h1>

<% @comments.each do |comment| %>
  <div class="card" style="width: 100%;">
    <div class="card-body">
      <h5 class="card-title">名前: <%= comment.name %></h5>
      <p class="card-text"><%= comment.content %></p>
      <p class="card-subtitle mb-2 text-muted">投稿日: <%= comment.created_at %></p>
      <%= link_to "こめんと削除", comment_path(comment.id), class: "btn btn-primary", method: :delete %>
    </div>
  </div>
  <hr>
<% end %>

<h2>コメント投稿</h2>
<% if @comment.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@comment, url: :comment_index) do |f| %>
  <%= f.text_field :name, placeholder: '名無しの鬼威惨', value: '名無しの鬼威惨' %>
  <%= f.text_field :content, placeholder: 'コメントを入力してください' %>
  <%= f.hidden_field :board_id, value: @board.id %>
  <%= f.submit %>
<% end %>
<%= link_to("戻る", board_index_path) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Keijban</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>